name: affordable heat
favicon: null
layout_spectrum: 0.5336019943933934
typography_spectrum: 0.5450512173119932
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7367962999269366
  lightness: 0.44051607651636004
  saturation: 0.5712391189299524
  rhythmicContrast: 0.17256275191903114
purpose: []
